spring:
  datasource:
    url: jdbc:postgresql://34.69.102.168:5432/spring-security
    username: mumbahiz
    password: mumbahiz123
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: vpc-demo-395212:us-central1:spring-security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
